#!/bin/sh
# $Id$
# Created 2003-08-29, Karl Berry.  Public domain.
# (Thanks to Akim Demaille.)

echo "Nothing to do to bootstrap CVS Texinfo (I think)."
exit 0

echo "Bootstrapping CVS Texinfo with:"

cmd="autoreconf --verbose --force --install --include=m4"
echo $cmd
$cmd

